### ISSUE TITLE
Unable to pass in switch for legacy implementation 

### ISSUE THREAD

**Issue by esaari** [ericbeland/browsermob-proxy-rb#31]
@jarib Is this fully compatible with the latest version of the bmp? We were forced to upgrade (version we had been using used SSLv3 and was incompatible with the latest OS upgrade we did) and I think that will require us to rewrite a few of the REST calls we're using in conjunction with this. Being short on time, I'd like to revert to the legacy (Jetty) implementation we were using to see if it just gets things working again. 

https://github.com/lightbody/browsermob-proxy#rest-api says you can specify a simple command line argument, `--use-littleproxy false` to revert to this. In `server.rb`, I see the only argument accepted is the path and port number: `process = ChildProcess.new(@path, "--port", @port.to_s)` 

Is it possible to use the above flag through the `server_options` hash or could an optional argument be added for additional flags to the `create_process` function?

**Comment by ericbeland** [comment]
Hi @esaari We are working on a new version of the proxy, and trying to bring in some of the legacy functionality. This gem will eventually point to a fork of that proxy once we publish it. Upstream work on the Browsermob proxy seems to have halted. Since you were short on time and this was submitted in 2016, I'm closing it for now.
